#!/bin/sh

# Set default start/boot
#-----------------------

logger -p local6.notice -t installer "app-miniupnpd-core - enabling MiniUPnP server"
systemctl enable miniupnpd.service >/dev/null 2>&1

logger -p local6.notice -t installer "app-miniupnpd-core - starting MiniUPnP server"
systemctl start miniupnpd.service >/dev/null 2>&1
